p_controller:
  ros__parameters:
    goal_tolerance: 0.5
    max_linear_speed: 0.5
    max_angular_speed: 0.2
    linear_gain: 1.0
    angular_gain: 1.0
    angle_thesold_rotate_in_place: 0.3490658503988659 # 20 deg
