p_controller:
  ros__parameters:
    goal_tolerance: 0.8

    # Linear movement
    min_linear_speed: -1.0
    max_linear_speed: 1.0
    linear_speed_deadzone: 0.4
    linear_gain: 1.0

    # Angular movement
    min_angular_speed: -1.0
    max_angular_speed: 1.0
    angular_speed_deadzone: 0.4
    angular_gain: 1.0
    angle_thesold_rotate_in_place: 0.3490658503988659 # 20 deg
