twist_mux_node:
  ros__parameters:
    topics:
      drive:
        topic: cmd_drive
        timeout: 0.2
        priority: 10
      controller:
        topic: cmd_ctrl
        timeout: 0.2
        priority: 100
      teleop:
        topic: cmd_teleop
        timeout: 0.2
        priority: 150
