topics:
  [
    "/controller/cmd_vel",
    "/battery_logs",
    "/imu_and_wheel_odom",
    "/joint_states",
    "/mapping/icp_odom",
    "/mapping/map",
    "/mapping/pose_in",
    "/mapping/scan_after_deskew",
    "/mapping/scan_after_input_filters",
    "/mti30/bias",
    "/mti30/data",
    "/mti30/data_raw",
    "/mti30/data_unbiased",
    "/mti30/imu_data_str",
    "/mti30/mag",
    "/mti30/time_reference",
    "/mti30/velocity",
    "/robot_description",
    "/rosout",
    "/rslidar128/packets",
    "/rslidar128/points",
    "/teleop/cmd_vel",
    "/teleop/joy",
    "/teleop/joy/set_feedback",
    "/teleop/lock_autonomy",
    "/tf",
    "/tf_static",
    "/vn100/bias",
    "/vn100/data",
    "/vn100/data_raw",
    "/vn100/data_unbiased",
    "/vn100/gnss",
    "/vn100/imu/original",
    "/vn100/magnetic",
    "/vn100/pose",
    "/vn100/pressure",
    "/vn100/temperature",
    "/vn100/time_gps",
    "/vn100/time_pps",
    "/vn100/time_startup",
    "/vn100/time_syncin",
    "/vn100/vectornav/raw/attitude",
    "/vn100/vectornav/raw/common",
    "/vn100/vectornav/raw/gps",
    "/vn100/vectornav/raw/gps2",
    "/vn100/vectornav/raw/imu",
    "/vn100/vectornav/raw/ins",
    "/vn100/vectornav/raw/time",
    "/vn100/vectornav/velocity_aiding",
    "/vn100/velocity_body",
    "/vtr/command",
    "/warthog/platform/cmd_vel",
    "/warthog/platform/emergency_stop",
    "/warthog/platform/motor/left/cmd_velocity",
    "/warthog/platform/motor/left/status/current_battery",
    "/warthog/platform/motor/left/status/fault",
    "/warthog/platform/motor/left/status/temperature_heatsink",
    "/warthog/platform/motor/left/status/temperature_motor",
    "/warthog/platform/motor/left/status/velocity",
    "/warthog/platform/motor/left/status/voltage_battery",
    "/warthog/platform/motor/right/cmd_velocity",
    "/warthog/platform/motor/right/status/current_battery",
    "/warthog/platform/motor/right/status/fault",
    "/warthog/platform/motor/right/status/temperature_heatsink",
    "/warthog/platform/motor/right/status/temperature_motor",
    "/warthog/platform/motor/right/status/velocity",
    "/warthog/platform/motor/right/status/voltage_battery",
    "/warthog/platform/odom",
    "/warthog/velocity_controller/cmd_vel_out",
    "/warthog/velocity_controller/transition_event",
    "/wiln/planned_trajectory",
    "/wiln/real_trajectory",
    "/wiln/state",
    "/drive/viz/geofence",
    "/drive/viz/predicted_path",
    "/drive/viz/goal",
    "/drive/viz/current_state",
    "/drive/viz/nb_steps_completed",
    "/drive/viz/help_msg",
  ]
